# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-09 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brew', '0003_auto_20171218_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.TextField(default=b''),
        ),
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.TextField(default=b''),
        ),
    ]
