# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-09 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brew', '0004_auto_20180109_0513'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default=b'', max_length=128),
        ),
    ]
