# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-09 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brew', '0005_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='profile',
            name='lon',
            field=models.FloatField(default=0.0),
        ),
    ]
