# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-07 20:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brew', '0007_auto_20180307_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brew.Profile', verbose_name=b'Fornecedor'),
        ),
    ]
